### PR TITLE
re-ordered the tables so it works for phpMyAdmin

### PR DESCRIPTION
**Pull request by NathanSchwantes**
I was having trouble getting the HarmonyBotSchema1.2.sql file being imported to phpMyAdmin

I didn't change anything other than the order of your tables. Please confirm these changes are okay because this version of the file worked for phpMyAdmin.

### CODE REVIEW

**Comment by LazerWulf214** [comment]
What was the issue phpMyAdmin was having?

**Comment by NathanSchwantes** [comment]
image

It would give me error messages like this. If a referenced table wasn't created first, it wouldn't be able to run the entire code.

**Comment by NathanSchwantes** [comment]
image

Once I re-ordered the tables it looks like this in phpMyAdmin.

**Review by LazerWulf214 — APPROVED** [review]
Looks good.

**Pull request merged**
